config/routes.rb
Rails.application.routes.draw do

  root 'search#index'
  get 'search/update_airline',  as: 'update_airline'
  get 'search/update_seat', as: 'update_seat'
  get 'search/update_aircraft', as: 'update_aircraft'
  get 'search/update_routes', as: 'update_routes'
  post 'search/result'

  scope '/admin' do
    get '/login' => 'session#new', as: 'login_path'
    post '/login' => 'session#create'
    get '/logout' => 'session#destroy'
    get '/dashboard' => 'dashboard#index', as: 'dashboard_path'

    "#{
    get '/aircraft/index', as: 'aircraft_index'
    get '/aircraft/edit', as: 'aircraft_edit'

    post '/aircraft/update', as: 'aircraft_update'
    post '/aircraft/create', as: 'aircraft_create'
    get '/aircraft/new', as: 'aircraft_new'
    delete '/aircraft/destroy', as: 'aircraft_destroy'
    }"

    "#{
    get '/airline/index', as: 'airline_index'
    get '/airline/edit', as: 'airline_edit'

    post '/airline/update', as: 'airline_update'
    post '/airline/create', as: 'airline_create'
    get '/airline/new', as: 'airline_new'
    delete '/airline/destroy', as: 'airline_destroy'
    }"

    "#{
    get '/alliance/index', as: 'alliance_index'
    get '/alliance/edit', as: 'alliance_edit'

    post '/alliance/update', as: 'alliance_update'
    post '/alliance/create', as: 'alliance_create'
    get '/alliance/new', as: 'alliance_new'
    delete '/alliance/destroy', as: 'alliance_destroy'
    }"
    "#{
    get '/mile/index', as: 'mile_index'
    get '/mile/edit', as: 'mile_edit'

    post '/mile/update', as: 'mile_update'
    post '/mile/create', as: 'mile_create'
    get '/mile/new', as: 'mile_new'
    delete '/mile/destroy', as: 'mile_destroy'
    }"

    "#{
    get '/route/index', as: 'route_index'
    get '/route/edit', as: 'route_edit'

    post '/route/update', as: 'route_update'
    post '/route/create', as: 'route_create'
    get '/route/new', as: 'route_new'
    delete '/route/destroy', as: 'route_destroy'
    }"

    "#{
    get '/create' => 'admins#new', as: 'admin_create'
    get '/all' => 'admins#index', as: 'admin_all'
    post '/create' => 'admins#create',as: 'admin_create_now'
    }"

  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="page-header">
      <h1>Welcome to Admin Dashboard <small> Good to see you <%= current_admin.name %></small></h1>
    </div>
  </div>

<div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <a href="#" class="list-group-item disabled bg-primary text-center">
        Select any table to manage
      </a>
      <a href="<%= airline_index_path%>" class="list-group-item">Airline</a>
      <a href="<%= aircraft_index_path%>" class="list-group-item">Aircraft</a>
      <a href="<%= alliance_index_path%>" class="list-group-item">Alliance</a>
      <a href="<%= mile_index_path%>" class="list-group-item">Mile</a>
      <a href="<%= route_index_path%>" class="list-group-item">Route</a>
    </div>
  </div>
  <div class="col-md-3">
    <div class="list-group">
      <a href="#" class="list-group-item disabled bg-primary text-center">
        Manage other Admins
      </a>
      <a href="<%= admin_create_path%>" class="list-group-item">Add a new Admin</a>
      <a href="<%= admin_all_path%>" class="list-group-item">View all admins</a>
    </div>
  </div>


</div>

</div>