config/routes.rb
Rails.application.routes.draw do

  root 'search#index'
  get 'search/update_airline',  as: 'update_airline'
  get 'search/update_seat', as: 'update_seat'
  get 'search/update_aircraft', as: 'update_aircraft'
  get 'search/update_routes', as: 'update_routes'
  post 'search/result'

  scope '/admin' do
    get '/login' => 'session#new', as: 'login_path'
    post '/login' => 'session#create'
    get '/logout' => 'session#destroy'
    get '/dashboard' => 'dashboard#index', as: 'dashboard_path'

    "#{
    get '/aircraft/index', as: 'aircraft_index'
    get '/aircraft/edit', as: 'aircraft_edit'

    post '/aircraft/update', as: 'aircraft_update'
    post '/aircraft/create', as: 'aircraft_create'
    get '/aircraft/new', as: 'aircraft_new'
    delete '/aircraft/destroy', as: 'aircraft_destroy'
    }"

    "#{
    get '/airline/index', as: 'airline_index'
    get '/airline/edit', as: 'airline_edit'

    post '/airline/update', as: 'airline_update'
    post '/airline/create', as: 'airline_create'
    get '/airline/new', as: 'airline_new'
    delete '/airline/destroy', as: 'airline_destroy'
    }"

    "#{
    get '/alliance/index', as: 'alliance_index'
    get '/alliance/edit', as: 'alliance_edit'

    post '/alliance/update', as: 'alliance_update'
    post '/alliance/create', as: 'alliance_create'
    get '/alliance/new', as: 'alliance_new'
    delete '/alliance/destroy', as: 'alliance_destroy'
    }"
    "#{
    get '/mile/index', as: 'mile_index'
    get '/mile/edit', as: 'mile_edit'

    post '/mile/update', as: 'mile_update'
    post '/mile/create', as: 'mile_create'
    get '/mile/new', as: 'mile_new'
    delete '/mile/destroy', as: 'mile_destroy'
    }"

    "#{
    get '/route/index', as: 'route_index'
    get '/route/edit', as: 'route_edit'

    post '/route/update', as: 'route_update'
    post '/route/create', as: 'route_create'
    get '/route/new', as: 'route_new'
    delete '/route/destroy', as: 'route_destroy'
    }"

    "#{
    get '/create' => 'admins#new', as: 'admin_create'
    get '/all' => 'admins#index', as: 'admin_all'
    post '/create' => 'admins#create',as: 'admin_create_now'
    }"

  end

end

app/models/alliance.rb
class Alliance < ActiveRecord::Base
  self.table_name = "tbl_alliances"
  self.primary_keys = :alliance, :airline

  attr_accessor :picture
end

app/controllers/alliance_controller.rb
class AllianceController < ApplicationController
  before_filter :authorize
  before_action :set_alliance, only: [:edit, :update, :destroy]

  require 'fileutils'

  def index
    @alliance = Alliance.all.sort
  end

  def new
    @alliance = Alliance.new
  end

  def edit
  end

  def create
    @alliance = Alliance.new(alliance_params)
    respond_to do |format|
      upload_picture
      @alliance.logo_alliance = @uploaded_io.try(:original_filename)|| " "
      if @alliance.save
        flash[:notice]='Alliance has been created'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      path =  Rails.root.join('public', 'images/alliance',  @alliance.logo_alliance||" ")
      if !@uploaded_io.try(:original_filename)
        delete_picture path if  File.exist?(path)
      end
      upload_picture
      @alliance.logo_alliance =  @uploaded_io.try(:original_filename)|| @alliance.logo_alliance
      if @alliance.update(alliance_params)
        flash[:notice]='Alliance has been updated'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :edit }
      end
    end
  end

  def destroy
    delete_picture Rails.root.join('public', 'images/alliance', @alliance.logo_alliance) if @alliance.logo_alliance
    @alliance.destroy
    respond_to do |format|
      flash[:notice]='Alliance has been deleted'
      format.html {  redirect_to :action => 'index' }
    end
  end

  private

  def set_alliance
    @i=0
    @alliance = Alliance.all.sort.map { |row | row if (@i+=1)==params[:index].to_i}.compact.first

  end

  def alliance_params
    params.require(:alliance).permit(:alliance, :airline, :logo_alliance, :picture)
  end

  def upload_picture
    @uploaded_io = alliance_params[:picture]
    if @uploaded_io
      File.open(Rails.root.join('public', 'images/alliance', @uploaded_io.original_filename), 'wb') do |file|
        file.write(@uploaded_io.read)
      end

    end
  end

  def delete_picture fname
    if  File.exist?(fname)
      FileUtils.rm(fname)
    end

  end




  #end of class
end

app/helpers/alliance_helper.rb
module AllianceHelper
end

app/views/alliance/edit.html.erb
<div class="container">
  <div class="row">


    <div class="col-md-6 col-md-offset-3">

      <%=form_for @alliance, url: alliance_update_path, html: {method: "post"} do |f| %>
          <div class="form-group">
            <label for="exampleInputEmail1">Alliance</label>
            <%= f.text_field :alliance, class:'form-control' %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Airline</label>
            <%= f.text_field :airline ,class:'form-control' %>
          </div>

          <%= hidden_field_tag :index, params[:index]%>
          <%=f.file_field :picture%>
          <div class="pull-right">
            <%= link_to 'Back', :alliance_index, class:'btn btn-warning' %>
            <%= f.submit :Submit, class: 'btn btn-success' %>
          </div>
          </div>


      <% end %>




      </div>












  <!-->

</div>
</div>

app/views/alliance/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-2 col-md-offset-10">


      <%= link_to fa_icon('plus', text: "Add new", right: false),{:controller => "alliance", :action => "new"}, class: 'pull-right btn btn-success push' %>



    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <tr>
          <th class="bg-primary">Serial#</th>
          <th class="bg-primary">Alliance</th>
          <th class="bg-primary">Airline</th>
          <th class="bg-primary">Logo</th>
          <th class="bg-primary">Manage</th>

        </tr>

        <% @alliance.each_with_index do |row,index |%>
            <tr>
              <th><%= index+=1 %></th>
              <th><%= row.alliance %></th>
              <th><%= row.airline %></th>

              <th><%= row.logo_alliance %></th>
              <th><%= link_to fa_icon('pencil lg'),{:controller => "alliance", :action => "edit", :index => index },class: "space" %>|
                <%= link_to fa_icon('trash-o lg'),{:controller => "alliance", :action => "destroy", :index => index }, method: :delete, class: 'space'%></th>
            </tr>
        <%end%>
      </table>
    </div>
  </div>

</div>

app/views/alliance/new.html.erb
<div class="container">
  <div class="row">


    <div class="col-md-6 col-md-offset-3">

      <%=form_for @alliance, url: alliance_create_path, html: {method: "post"} do |f| %>
          <div class="form-group">
            <label for="exampleInputEmail1">Alliance</label>
            <%= f.text_field :alliance, class:'form-control' %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Airline</label>
            <%= f.text_field :airline ,class:'form-control' %>
          </div>

          <%= hidden_field_tag :index, params[:index]%>
          <%=f.file_field :picture%>
          <div class="pull-right">
            <%= link_to 'Back', :alliance_index, class:'btn btn-warning' %>
            <%= f.submit :Submit, class: 'btn btn-success' %>
          </div>
          </div>


      <% end %>




      </div>












  <!-->

</div>
</div>