config/routes.rb
Rails.application.routes.draw do

  root 'search#index'
  get 'search/update_airline',  as: 'update_airline'
  get 'search/update_seat', as: 'update_seat'
  get 'search/update_aircraft', as: 'update_aircraft'
  get 'search/update_routes', as: 'update_routes'
  post 'search/result'

  scope '/admin' do
    get '/login' => 'session#new', as: 'login_path'
    post '/login' => 'session#create'
    get '/logout' => 'session#destroy'
    get '/dashboard' => 'dashboard#index', as: 'dashboard_path'

    "#{
    get '/aircraft/index', as: 'aircraft_index'
    get '/aircraft/edit', as: 'aircraft_edit'

    post '/aircraft/update', as: 'aircraft_update'
    post '/aircraft/create', as: 'aircraft_create'
    get '/aircraft/new', as: 'aircraft_new'
    delete '/aircraft/destroy', as: 'aircraft_destroy'
    }"

    "#{
    get '/airline/index', as: 'airline_index'
    get '/airline/edit', as: 'airline_edit'

    post '/airline/update', as: 'airline_update'
    post '/airline/create', as: 'airline_create'
    get '/airline/new', as: 'airline_new'
    delete '/airline/destroy', as: 'airline_destroy'
    }"

    "#{
    get '/alliance/index', as: 'alliance_index'
    get '/alliance/edit', as: 'alliance_edit'

    post '/alliance/update', as: 'alliance_update'
    post '/alliance/create', as: 'alliance_create'
    get '/alliance/new', as: 'alliance_new'
    delete '/alliance/destroy', as: 'alliance_destroy'
    }"
    "#{
    get '/mile/index', as: 'mile_index'
    get '/mile/edit', as: 'mile_edit'

    post '/mile/update', as: 'mile_update'
    post '/mile/create', as: 'mile_create'
    get '/mile/new', as: 'mile_new'
    delete '/mile/destroy', as: 'mile_destroy'
    }"

    "#{
    get '/route/index', as: 'route_index'
    get '/route/edit', as: 'route_edit'

    post '/route/update', as: 'route_update'
    post '/route/create', as: 'route_create'
    get '/route/new', as: 'route_new'
    delete '/route/destroy', as: 'route_destroy'
    }"

    "#{
    get '/create' => 'admins#new', as: 'admin_create'
    get '/all' => 'admins#index', as: 'admin_all'
    post '/create' => 'admins#create',as: 'admin_create_now'
    }"

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  self.table_name = "tbl_aircrafts"
  self.primary_keys = :airline, :aircraft, :seat
  attr_accessor :picture
  #belongs_to :airline
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  self.table_name = "tbl_airlines"
  self.primary_key = :airline

  attr_accessor :picture
end

app/models/alliance.rb
class Alliance < ActiveRecord::Base
  self.table_name = "tbl_alliances"
  self.primary_keys = :alliance, :airline

  attr_accessor :picture
end

app/models/mile.rb
class Mile < ActiveRecord::Base
  self.table_name = "tbl_miles"
  self.primary_keys = :alliance, :zone, :miles
end

app/models/route.rb
class Route < ActiveRecord::Base
  self.table_name = "tbl_routes"
  self.primary_keys = :airline, :start, :end,
                      :aircraft, :origin, :destination, :zone
 # belongs_to :mile
  #belongs_to :airline
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :authorize

  def index
    @admin = Admin.all
  end
  def new
    @admin = Admin.new
  end

  def create
    admin = Admin.new(admin_params)
    if admin.save
      session[:admin_id] = admin.id
      flash[:notice] = 'New admin has been created successfully'
      redirect_to :dashboard_path
    else
      flash[:alert]= 'Error occured'
    end
  end


  private
    def admin_params
      params.require(:admin_create_now).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/mile_controller.rb
class MileController < ApplicationController
  before_filter :authorize
  before_action :set_mile, only: [:edit, :update, :destroy]

  def index
    @mile = Mile.all.sort
  end


  def new
    @mile = Mile.new
  end

  def edit
  end

  def create
    @mile = Mile.new(mile_params)
    respond_to do |format|
     if @mile.save
        flash[:notice]='Mile has been created'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @mile.update(mile_params)
        flash[:notice]='Mile has been updated'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :edit }
      end
    end
  end

  def destroy
   @mile.destroy
    respond_to do |format|
      flash[:notice]='Mile has been deleted'
      format.html {  redirect_to :action => 'index' }

    end
  end

  private

  def set_mile
    @i=0
    @mile = Mile.all.sort.map { |row | row if (@i+=1)==params[:index].to_i}.compact.first

  end

  def mile_params
    params.require(:mile).permit(:alliance, :zone, :miles, :picture)
  end

#end of class
end

app/controllers/route_controller.rb
class RouteController < ApplicationController
  before_filter :authorize
  before_action :set_route, only: [:edit, :update, :destroy]

  def index
    @route = Route.all.sort
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    respond_to do |format|
      if @route.save
        flash[:notice]='Route has been created'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @route.update(route_params)
        flash[:notice]='Route has been updated'
        format.html { redirect_to :action => 'index' }
      else
        flash[:alert]= 'Error'
        format.html { render :edit }
      end
    end
  end

  def destroy
    @route.destroy
    respond_to do |format|
      flash[:notice]='Route has been deleted'
      format.html {  redirect_to :action => 'index' }

    end
  end

  private

  def set_route
    @i=0
    @route = Route.all.sort.map { |row | row if (@i+=1)==params[:index].to_i}.compact.first

  end

  def route_params
    params.require(:route).permit(:airline, :start, :end, :aircraft, :origin,:destination, :zone)
  end


  #end of class
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @alliance = Alliance.all
  end

  def update_airline
    if  params[:alliance_val] == 'Star Alliance'
      params[:alliance_val]= 'Star-Alliance'
    end
    @airline =  Alliance.where("alliance = ?", params[:alliance_val])
    respond_to do |format|
      format.js
    end
  end

  def update_seat
    @seat =  Aircraft.where("airline = ?", params[:airline_val]).pluck(:seat).uniq
    @airline_logo =  Airline.where("airline= ?", params[:airline_val]).first.airline_logo
    respond_to do |format|
      format.js
    end
  end

  def update_aircraft
    @aircraft = Aircraft.where("airline = ? AND seat =?",params[:airline_val],params[:product_val])
    #@logo = Aircraft.where("AIRLINE = ? AND SEAT =?",params[:airline],params[:seat]).pluck(:AIRCRAFT_LOGO).first

    respond_to do |format|
      format.js
    end
  end


  def update_routes
   @routes = Route.where("airline = ? AND aircraft = ?", params[:airline_val],  params[:aircraft_val])
   @aircraft_logo = Aircraft.where("airline = ? AND aircraft = ?", params[:airline_val],  params[:aircraft_val]).pluck(:aircraft_logo)

   respond_to do |format|
      format.js
    end
  end

  def result
    @routes = Route.where("airline = ? AND origin = ? AND destination = ?",
                          params[:search][:airline],params[:search][:routes1],params[:search][:routes2] )
    @miles = @routes.map{|route| Mile.where("zone = ?", route.zone.to_i)}

  respond_to do |format|
    format.html
  end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/aircraft_helper.rb
module AircraftHelper
end

app/helpers/airline_helper.rb
module AirlineHelper
end

app/helpers/alliance_helper.rb
module AllianceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/mile_helper.rb
module MileHelper
end

app/helpers/route_helper.rb
module RouteHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/admins/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">






      <div class="list-group">
          <% @admin.each_with_index do |row,index |%>
            <li class="list-group-item"><h3><%= row.name %></h3><span class="text-muted">Created <%= time_ago_in_words row.created_at%> ago</span></li>

          <%end%>

        </div>



    </div>


  </div>

</div>

app/views/admins/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="page-header text-center">
      <h3>Create a new Admin</h3>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for :admin_create_now, html: {method: "post"}, class:'form-horizontal' do |f| %>


        <div class="form-group col-md-8 col-md-offset-2">
          <div class="input-group">
            <div class="input-group-addon"><%= fa_icon 'user' %></div>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
          </div>
        </div>
        <div class="form-group col-md-8 col-md-offset-2">
          <div class="input-group">
            <div class="input-group-addon"><%= fa_icon 'lock' %></div>
            <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
          </div>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <div class="input-group">
            <div class="input-group-addon"><%= fa_icon 'lock' %></div>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'confirm password' %>
          </div>
        </div>


        <div class="form-group col-md-8 col-md-offset-2">

          <%= f.submit 'Create',class:"btn btn-success pull-right"%>

        </div>


    <%end%>

  </div>
</div>

app/views/layouts/_nav_bar.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b>Flights</b></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%if current_admin%>

            <li><a href="<%= dashboard_path_path %>"><button type="button" class="btn btn-default">Dashboard</button></a></li>
            <li><a href="<%= logout_path%>"><button type="button" class="btn btn-danger">Logout</button></a></li>
        <%else%>
            <li><a href= "<%= login_path%>"> <button type="button" class="btn btn-default">Admin Area</button></a></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightsAppFinal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav_bar'%>
<!--Alert notice for flash -->
<%if flash[:alert]%>
    <div class="container">
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <%=flash[:alert]%>
        </div>
    </div>
<%end%>
<!--End of alert notice for flash -->

<!--Alert notice for flash -->
<%if flash[:notice]%>
    <div class="container">
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%=flash[:notice]%>
      </div>
    </div>
<%end%>
<!--End of alert notice for flash -->

<%= yield %>

</body>
</html>

app/views/seat/_seat.html.erb
<option value=""></option>
<%  @seat.each do |airline| %>
    <option value="<%= airline %>"><%= airline %></option>
<% end%>